name: Build Check

on: push

jobs:
  build-check:
    name: enforce successful local build before deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show path info
        run: |
          pwd
          ls -lah

      - name: build-test-merge-publish
        # You may pin to the exact commit or the version.
        # uses: bbeesley/build-test-merge-publish@c942341b8ddf89ece7f1a9462aee06f943feb442
        uses: bbeesley/build-test-merge-publish@v1.1.0
        with:
          # Command to install package dependencies
          install-command: npm i
          # Command to run to build the package
          build-command: npm run build
          # Command to publish the package
          # release-command: # optional, default is npm run release
          # Branch to release from
          main-branch: main
          # Method to use to merge dependabot PRs
          # merge-method: # optional, default is REBASE
          # Private registry to auth with for install/publish
          # private-npm-registry: # optional
          # Auth token to use with private npm registry
          # private-npm-token: # optional
          # The github username of a bot whose PRs should be auto approved and auto merged
          # auto-merge-bot: # optional
